services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cellmapper-client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - cellmapper-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: cellmapper-server
    environment:
      - NODE_ENV=production
      - NODE_CONFIG_ENV=docker
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - cellmapper-network
    # Note: Make sure to stop any local PostgreSQL server before starting this container
    # Run: brew services stop postgresql@14 (or equivalent for your system)

  postgres:
    image: postgis/postgis:15-3.3
    container_name: cellmapper-postgres
    environment:
      POSTGRES_USER: cellmapper
      POSTGRES_PASSWORD: cellmapper
      POSTGRES_DB: cellmapper
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cellmapper -d cellmapper"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cellmapper-network

  redis:
    image: redis:7
    container_name: cellmapper-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cellmapper-network

networks:
  cellmapper-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
